# Compose2nix command
# compose2nix -inputs sonarqube.yml -output sonarqube.nix -runtime docker -project=sonarqube

# DONT FORGET TO BUILD THE IMAGES FIRST! AND MAKE SURE THEIR ALIASES ARE SET (hldup/csengoserver)
# Todo add values from .env file via ${}

services:
  csengo-v2-session-store:
    container_name: csengo-v2-session-store
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass session-store-password
    networks:
      - csengo-v2

  csengo-v2-postgres:
    container_name: csengo-v2-postgres
    image: postgres:16.6
    restart: always
    environment:
      POSTGRES_USER: csengo
      POSTGRES_PASSWORD: csengo
      POSTGRES_DB: csengo
    volumes:
      - csengo-v2_db:/var/lib/postgresql/data
    networks:
      - csengo-v2

  csengo-ts-server-v2:
    container_name: csengo-ts-server-v2
    image: ghcr.io/tgyakos/csengo-ts-server-v2/app:latest
    restart: always
    volumes:
      - csengo-v2_sounds:/data
    ports:
      - "7666:3300"
    depends_on:
      - csengo-v2-session-store
      - csengo-v2-postgres
    networks:
      - csengo-v2
    environment:
      PORT: 3300
      DATABASE_URL: "postgresql://csengo:csengo@csengo-v2-postgres:5432/csengo?schema=public"
      UPLOAD_PATH: "./data/audio"
      TOKEN_SECRET: "3]{{[45qEFK161qhPa86Gi}jP]g{J>3{G18(gLSqc}G(jZgBGQYy{n>a7BPWq(F1"
      JWT_SECRET: "2yYRf9Xx3j2S8z23Gt[gu<b94<6gvTS[TQUSUx]}88gi<36{G]rHTy]<zr]B([[n"
      SESSION_STORE_PASSWORD: "session-store-password"
      SESSION_STORE_HOST: "csengo-v2-session-store"
      SESSION_STORE_PORT: 6379
      CORS_ORIGIN: ".*[a-z0-9]*.pollak.info"
      CORS_DOMAIN: "pollak.info"
      DEV: "false"

  csengo-ts-client-v2:
    container_name: csengo-ts-client-v2
    image: ghcr.io/tgyakos/csengo-ts-client-v2/app:latest
    ports:
      - "7665:80"
    networks:
      - csengo-v2


  csengo-v2-pgadmin:
    container_name: csengo-v2-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "7667:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@4o1x5.dev
      PGADMIN_DEFAULT_USERNAME: admin
      PGADMIN_DEFAULT_PASSWORD: t678ogryeilrgep89y35y8o9wb896yp4*^&Ygsdfe
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
    volumes:
      - csengo-v2_pgadmin:/var/lib/pgadmin
    networks:
      - csengo-v2

networks:
  csengo-v2:

volumes:
  csengo-v2_db:
  csengo-v2_sounds:
  csengo-v2_pgadmin:
