# Compose2nix command
# compose2nix -inputs sonarqube.yml -output sonarqube.nix -runtime docker -project=sonarqube

# DONT FORGET TO BUILD THE IMAGES FIRST! AND MAKE SURE THEIR ALIASES ARE SET (hldup/csengoserver)
# Todo add values from .env file via ${}
services:
  csengoserver:
    container_name: csengoserver
    image: berryes/csengoserver
    restart: always
    hostname: csengoserver
    volumes:
      - /lv/csengo/sounds:/usr/csengo/data
    environment:
      PORT: 7666
      HCAPTCHA_SECRET: 0x438d6ccF49253aC89b82FdDf2B7680400C7C5f62
      TOKEN_SECRET: Xpoollak!@aCsDdCVpdjd88269037190zbcGIOcv6ioVIgs
      DB_NAME: 1ogn3esc2
      DB_USER: pollakCSengodhCuCV82ihd
      DB_PASS: FfjDcdosdis92Fh3d
      DB_HOST: csengopostgres
      SESSION_STORE_PASSWORD: HIebSbfqyzPL5pI4dY5d4Ilpju1WSRP6YlbCkm6GK
      SESSION_STORE_HOST: csengosessionstore
      SESSION_STORE_PORT: 6379
      DEV: 0
    ports:
      - "7666:7666"
    networks:
      - csengo


  csengoclient:
    container_name: csengoclient
    image: berryes/csengoclient
    hostname: csengoclient
    environment:
      VITE_API_URL: "https://localhost:7666/api"
    ports:
      - "7665:8080"
    networks:
      - csengo

  sessionstore:
    container_name: sessionstore
    image: redis:latest
    restart: always
    hostname: csengosessionstore
    command: redis-server --save 20 1 --loglevel warning --requirepass HIebSbfqyzPL5pI4dY5d4Ilpju1WSRP6YlbCkm6GK
    ports:
      - "6379:6379"
    networks:
      - csengo

  csengopostgres:
    container_name: csengopostgres
    image: "postgres:latest"
    restart: always
    hostname: csengopostgres
    ports:
      - "5582:5432"
    environment:
      POSTGRES_USER: pollakCSengodhCuCV82ihd
      POSTGRES_PASSWORD: FfjDcdosdis92Fh3d
      POSTGRES_DB: 1ogn3esc2
    volumes:
      - /lv/database:/var/lib/postgresql/data
    networks:
      - csengo

networks:
  csengo:
